# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: pyqvrpro
version: 1.0.3
slug: pyqvrpro
description: "Pyqvrpro for connection to QVR pro to get recording"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  5000/tcp: 5000

init: false

options:
  QVRPRO_USER: "username"
  QVRPRO_PW: "password"
  QVRPRO_HOST: "192.168.1.3"
  QVRPRO_PROTOCOL: "http"
  QVRPRO_PORT: 80
  CAMERA_GUID: ""
  VERIFY_SSL: 0

schema:
  QVRPRO_USER: "str"
  QVRPRO_PW: "str"
  QVRPRO_HOST: "str"
  QVRPRO_PROTOCOL: "str"
  QVRPRO_PORT: "int?"
  CAMERA_GUID: "str?"
  VERIFY_SSL: "int?"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
